services:
  server:
    build:
      context: ./server/
    env_file:
      - ./server/.env
    ports:
      - 8080:8080
    volumes:
      - .:/code
    command: /bin/bash -c "/code/server/scripts/venv.sh &&
                           /code/server/scripts/run.sh"
  server-bash:
    build:
      context: ./server/
    env_file:
      - ./server/.env
    ports:
      - 8080:8080
    volumes:
      - .:/code
    command: /bin/bash -c "/code/server/scripts/venv.sh &&
                           /bin/bash"
